# "Create Issue Branch" App cs_configuration
# https://github.com/marketplace/actions/create-issue-branch

mode: chatops
silent: false
branchName: 'short'
autoCloseIssue: true

branches:
  - label: feature
    prefix: grades/feature/
  - label: bug
    prefix: grades/bugfix/
  - label: '*'
    prefix: grades/issues/