# "Create Issue Branch" App cs_configuration
# https://github.com/marketplace/actions/create-issue-branch

mode: auto
silent: true
branchName: 'grades_${issue.number}-${issue.title}'
# autoCloseIssue: true

branches:
  - label: feature
    name: grades_developement
    # prefix: grades/
#   - label: bug
#     name: staging
#     prefix: bugfix/
  - label: '*'
    name: grades_developement
    # prefix: grades/